site_name: RIFTS Hardware Documentation

theme:
  name: material

docs_dir: docs

markdown_extensions:
  - admonition
  - pymdownx.details

nav:
  - Home: index.md

  - RF-Shielded Enclosures:
      - RFSoC 4x2 Portable Field Enclosure: hardware/rfsoc-4x2.md
      - ZCU216 Rack-Mounted Enclosure: hardware/zcu216.md

  - Antenna Systems:
      - OmniLOG PRO 1030 N Antenna Mount: antenna/omnilog.md

  - Supporting Hardware: hardware/accessories.md

  - Electronics Reference Models: electronics-reference-models.md